### ISSUE TITLE
Rename npm package peer-pad-core

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/peerpad-core#11]
I just

```sh
$ npm i peer-pad-core@0.11
npm ERR! code E404
npm ERR! 404 Not Found: peer-pad-core@0.11
```

and it was no fun.

**Comment by olizilla** [comment]
I see that the peerpad repo got renamed peer-pad. I know it's low value but let's rename the npm packages to match.

**Comment by pgte** [comment]
Tried publishing after renaming it, but got the following error:

<img width="571" alt="1__bash_and_package_json_ _peerpad-core" src="https://user-images.githubusercontent.com/47910/39743959-8d3b8666-529a-11e8-81a8-0ea2acc96f2e.png">

Does anyone have experience with how to solve this?

**Comment by cjoulain** [comment]
Hi all. Saw your tweet about this. Our typo-squat rule prevents similarly named packages being published. Currently, @pgte scope owns the `peerpad-core` package, which is preventing `peer-pad-core` from being published. If you wish to publish the `peer-pad-core` package, we'd have to deprecate the former package. Alternately, you may publish a scoped package.

Please let me know which option you prefer.

**Comment by pgte** [comment]
@cjoulain thank you! I prefer that you deprecate it so that I can publish.

**Comment by cjoulain** [comment]
Hi @pgte. We recently deprecated transferred `peerpad-core` and transferred `peer-pad-core` over to your username. Let us know have any troubles publishing to the new package.

**Comment by pgte** [comment]
It worked, thank you!
