### ISSUE TITLE
perparations for js-ipfs 0.30

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/peerpad-core#20]
I upgraded the following dependencies in preparation for js-ipfs 0.30, and ran the e2e tests from peer-pad and they passed!:

```js
    "ipfs": "github:ipfs/js-ipfs",
    "libp2p-crypto": "^0.13.0",
```

https://github.com/ipfs/js-ipfs/issues/1375

**Comment by daviddias** [comment]
Done with https://github.com/ipfs-shipyard/peer-pad-core/pull/21
