### ISSUE TITLE
support math pad type

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad-core#3]

**Comment by pgte** [comment]
Provided by f05268846beb9c14f5398637bce222ebecd4ddde

**Comment by pgte** [comment]
Landed on v0.6.1

**Comment by nicola** [comment]
@pgte without https://github.com/ipfs-shipyard/peerpad-core/pull/2/files how would the snapshot work with formulas..?

**Comment by pgte** [comment]
Snapshot capability for math pad provided by a1324af51dc860b3952c27c58974f9ae126cc1d3
