### ISSUE TITLE
sync after reconnect fails one way

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/peerpad-core#7]
How to reproduce:

* Open one browser
* Start a new pad
* Open it in another browser
* Do some edits
* Shut down network
* Make sure peers no longer believe they are connected to each other
* Make edits on both browsers
* Reconnect
* Notice how the changes in one are propagated to the other, but not vice-versa

(In this state, making more changes in other makes pads sync again, solving the issue).

**Comment by daviddias** [comment]
I believe this is the issue @flyingzumwalt experienced

**Comment by pgte** [comment]
Need #8 solved before to be able to debug this one.

**Comment by pgte** [comment]
Perhaps related:
Also observed this in the wild, when reconnecting:
<img width="366" alt="hey12ab" src="https://user-images.githubusercontent.com/47910/33685196-bb16de36-dac8-11e7-8ed9-c783603da7be.png">

**Comment by pgte** [comment]
Data loss after reconnect stopped happening with y-ipfs-connector@2.1.2 and js-libp2p-websocket-star-rendezvous@0.2.2.
